default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  database: jets_sms
  username: <%= ENV['DB_USERNAME'] %> 
  password:  <%= ENV['DB_PASSWORD'] %> 
  host: <%= ENV['DB_HOST'] %>
  reconnect: true

development:
  <<: *default
  database: jets_sms

test:
  <<: *default
  database: jets_sms

production:
  <<: *default
  database: jets_sms
